<a href="https://colab.research.google.com/github/alexandreIFB/projects_colabority/blob/master/P3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd

dictSeqs = {}

#Leitura de um Arquivo
filename_one = "/content/arquivo1.fasta"
filename_two = "/content/arquivo2.fasta"

fp_one = open(filename_one).readlines()
del fp_one[0]
seq_one = "".join(fp_one)

fp_two = open(filename_two).readlines()
del fp_two[0]
seq_two = "".join(fp_two)

seq_one = [0,0] + list(seq_one)
seq_two = [0,0] + list(seq_two)

matriz = [seq_one]

for y in range(1, len(seq_two)):
  linha = []
  linha.append(seq_two[y])
  for x in range(1, len(seq_one)):
      linha.append(0)
  matriz.append(linha)

matriz = np.array(matriz)

for y in range(1,len(seq_one)):
  matriz[1,y] = (y-1) * -2

for y in range(1,len(seq_two)):
  matriz[y,1] = (y-1) * -2


for y in range(2,len(seq_one)):
  for x in range(2, len(seq_two)):
    lista = []
    if( matriz[0,y] == matriz[x,0] ):
      lista.append(int(matriz[x-1,y-1]) + 2)
    else:
      lista.append(int(matriz[x-1,y-1]) - 1)
    lista.append(int(matriz[x-1,y]) - 2)
    lista.append(int(matriz[x,y-1]) - 2)
    lista.sort()
    matriz[x,y] = lista[2]


cont = 0
linha = len(seq_two) -1 
coluna = len(seq_one) -1

result_one = ''
result_two = ''

## Verifica o caminho inverso para montar a sequencia
while(linha > 1):
  #print(matriz[linha,coluna])
  if(matriz[0,coluna] == matriz[linha, 0]):
    if((int(matriz[linha-1,coluna-1]) + 2) == int(matriz[linha,coluna])):
      #print('Match')
      result_one += matriz[0,coluna]
      result_two += matriz[linha,0]
      linha = linha - 1;
      coluna = coluna - 1;
      continue
  else:
    if((int(matriz[linha-1,coluna-1]) - 1) == int(matriz[linha,coluna])):
      #print('Dismatch')
      result_one += matriz[0,coluna]
      result_two += matriz[linha,0]
      linha = linha - 1;
      coluna = coluna - 1;
      continue

  if((int(matriz[linha,coluna-1]) - 2) == int(matriz[linha,coluna])):
    result_one += matriz[0,coluna]
    result_two += '-'
    coluna = coluna - 1
    continue


  if((int(matriz[linha - 1,coluna]) - 2) == int(matriz[linha,coluna])):
    result_one += '-'
    result_two += matriz[linha,0]
    linha = linha - 1
    continue

print(result_one[::-1])
print(result_two[::-1])

panda_df = pd.DataFrame(data = matriz[1:, 1:],
                        index = matriz[1:, 0],
                        columns = matriz[0, 1:])

# Mostra a matriz pontuação
display(panda_df)

TGCTCGTA
T--TCATA

     0   T   G   C   T    C    G    T    A
0    0  -2  -4  -6  -8  -10  -12  -14  -16
T   -2   2   0  -2  -4   -6   -8  -10  -12
T   -4   0   1  -1   0   -2   -4   -6   -8
C   -6  -2  -1   3   1    2    0   -2   -4
A   -8  -4  -3   1   2    0    1   -1    0
T  -10  -6  -5  -1   3    1   -1    3    1
A  -12  -8  -7  -3   1    2    0    1    5